language: python
sudo: false
dist: bionic

cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"

branches:
  only:
    - master

env:
  matrix:
   - ''  # main tests
   - SAMPLE_APP=1  # sample app tests

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint
  - jslint ./django_ipam/static/django-ipam/js/*.js

install:
  - pip install "django>=2.0,<2.3"
  - python setup.py -q develop

script:
  - >
    openwisp-utils-qa-checks --migration-path "./django_ipam/migrations/ ./tests/sample_ipam/migrations/"
    --skip-checkmakemigrations
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $SAMPLE_APP != "1" ]]; then
      openwisp-utils-qa-checks \
        --skip-isort \
        --skip-flake8 \
        --skip-checkmigrations \
        --skip-checkendline \
        --skip-checkcommit \
        --migration-module django_ipam
    fi
  - coverage run --source=django_ipam runtests.py

after_success:
  - coveralls
