language: python
sudo: false
dist: bionic

cache: pip

python:
  - "3.5"

branches:
  only:
    - master

env:
  matrix:
   - ''  # main tests
   - SAMPLE_APP=1  # sample app tests

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - flake8
  - isort --check-only --recursive --diff .
  - ./runcheckmigration
  - npm install -g jslint
  - jslint ./django_ipam/static/django-ipam/js/*.js

install:
  - pip install "django>=2.0,<2.3"
  - python setup.py -q develop

before_script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $SAMPLE_APP != "1" ]]; then
      OUTPUT=$(./tests/manage.py makemigrations --dry-run django_ipam)
      echo $OUTPUT
      echo $OUTPUT | grep "No changes detected"
    fi
    
script:
  - coverage run --source=django_ipam runtests.py
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      # gets commit message of last commit before pull request merge
      COMMIT_MESSAGE=$(git log $TRAVIS_PULL_REQUEST_SHA --format=%B -n 1)
      printf "Checking commit message:\n\n"
      printf "$COMMIT_MESSAGE\n\n"
      checkcommit --message "$COMMIT_MESSAGE"
    fi

after_success:
  - coveralls
